#ifndef VG_STROKER_H
#define VG_STROKER_H

#include <stdint.h>
#include "vg.h"

namespace vg
{
struct Stroker;

/*
* Destination buffers for the geometry generated by the stroker (see StrokerSink).
*/
struct StrokerOutput
{
	float* m_PosBuffer;      // numVertices * 2 floats (no alignment requirements)
	uint32_t* m_ColorBuffer; // numVertices colors. Required only by the functions which generate colors (AA fills and strokes).
	uint16_t* m_IndexBuffer; // numIndices indices
	uint16_t m_BaseVertex;   // Added to all generated indices
};

/*
* Called by the stroker when it knows the exact amount of geometry it's going to generate (before generating it).
* Returns false if the stroker should use its internal buffers instead.
*/
typedef bool (*StrokerAllocFn)(void* userData, uint32_t numVertices, uint32_t numIndices, StrokerOutput* output);

/*
* Optional parameter of the functions below which allows the caller to have the geometry written directly
* into its own buffers (e.g. a vertex buffer) instead of the stroker's internal buffers, avoiding a copy.
* When the allocation function succeeds, the returned mesh points to the caller's buffers and its indices
* include m_BaseVertex.
*/
struct StrokerSink
{
	StrokerAllocFn m_AllocFn;
	void* m_UserData;
};

Stroker* createStroker(bx::AllocatorI* allocator);
void destroyStroker(Stroker* stroker);

void strokerReset(Stroker* stroker, float scale, float tesselationTolerance, float fringeWidth);

/* Geometry
* @----------------------------------@
* |                                  |
* |                                  |
* a                                  b
* |                                  |
* |                                  |
* @----------------------------------@
*
* Generates positions and indices. All vertices have the same color.
* Polyline vertices (a, b) are not part of the geometry.
*/
void strokerPolylineStroke(Stroker* stroker, Mesh* mesh, const float* vertexList, uint32_t numVertices, bool isClosed, float strokeWidth, LineCap::Enum lineCap, LineJoin::Enum lineJoin, const StrokerSink* sink = nullptr);

/* Geometry
* #----------------------------------#
* |             AA Fringe            |
* @----------------------------------@
* |                                  |
* |                                  |
* a                                  b
* |                                  |
* |                                  |
* @----------------------------------@
* |             AA Fringe            |
* #----------------------------------#
*
* Generates positions, colors and indices.
* Outer vertices (#) have alpha = 0 and inner vertices (@) have alpha = initial value.
* Polyline vertices (a, b) are not part of the geometry.
*/
void strokerPolylineStrokeAA(Stroker* stroker, Mesh* mesh, const float* vertexList, uint32_t numVertices, bool isClosed, Color color, float strokeWidth, LineCap::Enum lineCap, LineJoin::Enum lineJoin, const StrokerSink* sink = nullptr);

/* Geometry
* #----------------------------------#
* |             AA Fringe            |
* a----------------------------------b
* |             AA Fringe            |
* #----------------------------------#
*
* Generates positions, colors and indices.
* Outer vertices (#) have alpha = 0 and inner vertices (a,b) have alpha = initial value.
*/
void strokerPolylineStrokeAAThin(Stroker* stroker, Mesh* mesh, const float* vertexList, uint32_t numVertices, bool isClosed, Color color, LineCap::Enum lineCap, LineJoin::Enum lineJoin, const StrokerSink* sink = nullptr);

/*
* Generates only indices (a triangle fan).
* Positions are the initial polygon vertices (the same pointer is returned in the mesh).
* All vertices have the same color.
*/
void strokerConvexFill(Stroker* stroker, Mesh* mesh, const float* vertexList, uint32_t numVertices);

/*
* Generates positions, colors and indices
*/
void strokerConvexFillAA(Stroker* stroker, Mesh* mesh, const float* vertexList, uint32_t numVertices, uint32_t color, const StrokerSink* sink = nullptr);

bool strokerConcaveFillBegin(Stroker* stroker);
void strokerConcaveFillAddContour(Stroker* stroker, const float* vertexList, uint32_t numVertices);

/*
* Generates positions and indices.
* All vertices have the same color.
*/
bool strokerConcaveFillEnd(Stroker* stroker, Mesh* mesh, FillRule::Enum fillRule);

/*
* Generates positions, colors and indices
*/
bool strokerConcaveFillEndAA(Stroker* stroker, Mesh* mesh, uint32_t color, FillRule::Enum fillRule);

/*
* Index ranges of the geometry generated by strokerConcaveFillEndStencil(). The ranges are consecutive in the
* index buffer, in this order; the remaining 6 indices are the cover quad (the bounding box of the contours).
*/
struct StencilFillGeometry
{
	uint32_t m_NumFanIndices;         // Triangle fans of the contours (stencil pass)
	uint32_t m_NumOuterFringeIndices; // Fringe strips on both sides of every contour segment, alpha 0.5 (on the segment) -> 0
	uint32_t m_NumInnerLeftIndices;   // Fringe strips on the left side of every contour segment, alpha 0.5 (on the segment) -> 1
	uint32_t m_NumInnerRightIndices;  // Fringe strips on the right side of every contour segment, alpha 0.5 (on the segment) -> 1
};

/*
* Generates the geometry of a stencil-then-cover fill of the contours (no tesselation): the triangle fans of
* the contours, the AA fringe strips around every contour segment (aa only, see StencilFillGeometry) and the
* cover quad. Generates positions, colors and indices. The vertices on the contours have half the alpha of color.
*/
bool strokerConcaveFillEndStencil(Stroker* stroker, Mesh* mesh, uint32_t color, bool aa, StencilFillGeometry* geom, const StrokerSink* sink = nullptr);
}

#endif
